name:                pinary
version:             0.1.0.0
github:              "jdschwar/pinary"
license:             MIT
author:              "Jeremy Schwartz"
maintainer:          "j.schwartz564@icloud.com"
copyright:           "2020 Jeremy Schwartz"

extra-source-files:
- README.md

description: A marginally useful library for converting binary to printable text.

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- containers >= 0.6 && < 0.7
- digits >= 0.3 && < 0.4
- split >= 0.2 && < 0.3
- mtl >= 2.2 && < 2.3
- utf8-string >= 1.0 && < 1.1

library:
  source-dirs: src

executables:
  pinary:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pinary
    - cmdargs >= 0.10 && < 0.11

tests:
  pinary-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pinary
    - HUnit >= 1.4
    - QuickCheck >= 2.13
